{
 "title": "Finance",
 "time": { "from": "2022-03-02T19:36:59.941Z", "to": "2022-03-03T00:56:59.941Z" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "category",
    "query": "select name from finance.category"
   },
   {
    "name": "dolar",
    "label": "dolar (R$)",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Movimentações do Ano",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(case\n    when inv.currency = \"USD\"\n      then total * $dolar\n    else total\n  end) as \"Total\" FROM finance.transaction tran\ninner join finance.investment inv on inv.id = tran.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere YEAR(negotiationDate) = YEAR(CURRENT_DATE()) and cat.name in($category);"
    }
   ]
  },
  {
   "title": "Provendos do Ano",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(case\n    when inv.currency = \"USD\"\n      then(dy.total - dy.fees) * $dolar\n    else (dy.total - dy.fees)\n  end) as \"Total\" FROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere YEAR(dueDate) = YEAR(CURRENT_DATE()) and dy.status = \"PAID\" and cat.name in($category);"
    }
   ]
  },
  {
   "title": "Retorno do Mês",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (sum(case\n    when inv.currency = \"USD\"\n      then dy.total * $dolar\n    else dy.total\n  end)/ (select sum(case\n    when currency = \"USD\"\n      then balance * $dolar\n    else balance\n  end) from finance.investment)) * 100 as \"Total\" FROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere YEAR(dueDate) = YEAR(CURRENT_DATE()) and dy.status = \"PAID\" and cat.name in($category);"
    }
   ]
  },
  {
   "title": "Patrimônio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(case\n    when inv.currency = \"USD\"\n      then balance * $dolar\n    else balance\n  end) as \"Total\"\nFROM finance.investment inv\ninner join finance.category cat on cat.id = inv.categoryId\nwhere cat.name in($category)"
    }
   ]
  },
  {
   "title": "Provendos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(case\n    when inv.currency = \"USD\"\n      then total * $dolar\n    else total\n  end) as \"Total\" FROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere cat.name in($category) and dy.status = \"PAID\";"
    }
   ]
  },
  {
   "title": "Retorno",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\n  (\n  \tselect sum(total)\n    end FROM finance.dividends dy\n  \tinner join finance.investment inv on inv.id = dy.investmentId\n  \tinner join finance.category cat on cat.id = inv.categoryId\n  \twhere cat.name in($category) and dy.status = \"PAID\" and cat.name != \"CRIPTOMOEDA\"\n  ) / sum(total)\n) * 100 as \"Percentual\" FROM finance.transaction tran\ninner join finance.investment inv on inv.id = tran.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere cat.name in($category) and cat.name != \"CRIPTOMOEDA\""
    }
   ]
  },
  {
   "title": "Valor Atual da carteira (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n(SUM(variationTotal) / SUM(balance)) * 100 as \"Percentual\"\nFROM finance.investment inv\ninner join finance.category cat on cat.id = inv.categoryId\nwhere cat.name in($category) and  inv.priceDay is not null"
    }
   ]
  },
  {
   "title": "Valor Atual da carteira (R$)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(case\n    when inv.currency = \"USD\"\n      then variationTotal * $dolar\n    else variationTotal\n  end) as \"Total\"\nFROM finance.investment inv\ninner join finance.category cat on cat.id = inv.categoryId\nwhere cat.name in($category) and inv.priceDay is not null"
    }
   ]
  },
  {
   "title": "Cotação + Dividendos + Lucros/Prejuizo",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\n  (\n    select \n      sum(case\n        when inv.currency = \"USD\"\n          then total * $dolar\n        else total\n      end) from finance.dividends dy\n    inner join finance.investment inv on inv.id = dy.investmentId\n    inner join finance.category cat on cat.id = inv.categoryId\n    where dy.status = \"PAID\" and cat.name in($category)\n  ) + \n  sum(case\n    when inv.currency = \"USD\"\n      then variationTotal * $dolar\n    else variationTotal\n  end) + \n  (\n    select \n      sum(case\n        when inv.currency = \"USD\"\n          then tran.profit * $dolar\n        else tran.profit\n      end) from finance.transaction tran\n    inner join finance.investment inv on inv.id = tran.investmentId\n    inner join finance.category cat on cat.id = inv.categoryId\n    where cat.name in($category)\n  )\n)\nAS \"Total\"\nFROM finance.investment inv\ninner join finance.category cat on cat.id = inv.categoryId\nwhere inv.priceDay is not null and inv.balance > 0 and cat.name in($category)"
    }
   ]
  },
  {
   "title": "Variação Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  case\n    when currency = \"USD\"\n      then sum(variationDayTotal) * $dolar\n    else sum(variationDayTotal)\n  end  AS \"Total\"\nFROM finance.view_investment\nwhere category ->> \"$.name\" in($category)"
    }
   ]
  },
  {
   "title": "Lucro / Prejuizo do dia",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \ncase\n  when currency = \"USD\"\n    then sum((priceDay - previousClosePrice) * qnt) * $dolar\n  else sum((priceDay - previousClosePrice) * qnt)\nend AS \"Total\" from finance.view_investment\nwhere priceDay is not null and previousClosePrice is not null and balance > 0 and category ->> \"$.name\" in($category)"
    }
   ]
  },
  {
   "title": "Cotação do dia",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  inv.updatedAt AS \"time\",\n  case\n    when inv.currency = \"USD\"\n      then inv.priceDay * $dolar\n    else inv.priceDay\n  end AS \"Preço\",\n  inv.name\nFROM finance.investment inv\ninner join finance.category cat on cat.id = inv.categoryId\nwhere cat.name in($category) and inv.balance > 0\nORDER BY inv.updatedAt "
    }
   ]
  },
  {
   "title": "Variação do dia",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  inv.updatedAt AS \"time\",\n  case\n    when inv.currency = \"USD\"\n      then inv.variationDay * $dolar\n    else inv.variationDay\n  end AS \"Preço\",\n  inv.name\nFROM finance.investment inv\ninner join finance.category cat on cat.id = inv.categoryId\nwhere cat.name in($category) and inv.balance > 0\nORDER BY inv.updatedAt"
    }
   ]
  },
  {
   "title": "Carteira",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select\ninv.logoUrl as \"Logo\",\ninv.name as \"Código\",\ninv.qnt as \"Total de Cotas\",\ninv.balance as \"Total de Aportes\",\n(\n  select sum(dy.total - dy.fees) from finance.dividends dy where dy.investmentId = inv.id and dy.status = \"PAID\"\n) as \"Dividendos\",\ninv.priceAverage as \"Preço Médio\",\ninv.priceDay as \"Cotação Hoje\",\nsum(inv.balance + inv.variationTotal) as \"Saldo Atual\",\ninv.variationTotal as \"Lucro/Prejuízo\",\ninv.changePercentTotal as \"Saldo (%)\",\ninv.percent as \"(%) Da Carteira\",\nreplace(inv.category -> \"$.name\", '\"', '') as \"Categoria\",\ninv.sector as \"Seguemento\"\nfrom finance.view_investment inv\nwhere balance > 0 and category ->> \"$.name\" in($category)\ngroup by inv.id\norder by inv.balance desc"
    }
   ]
  },
  {
   "title": "Últimas compras (1M)",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\ninv.name as \"Código\",\ntran.price as \"Preço\",\nsum(tran.qnt) as \"Qnt\",\ncase\n\twhen tran.type = \"SELL\" THEN tran.total - ABS(tran.profit)\n  else tran.total\nend as \"Total\",\nDATE_FORMAT(tran.negotiationDate, \"%d/%m/%y\") as \"Data\"\nFROM finance.transaction tran\ninner join finance.investment inv on inv.id = tran.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere negotiationDate > last_day(now() - INTERVAL 1 MONTH) AND cat.name in($category)\ngroup by inv.id, tran.negotiationDate, tran.createdAt\norder by tran.negotiationDate, tran.createdAt\n"
    }
   ]
  },
  {
   "title": "Dividendo Provisionado",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dy.updatedAt AS \"time\",\n  case\n    when inv.currency = \"USD\"\n      then sum(dy.total - dy.fees) * $dolar\n    else sum(dy.total - dy.fees)\n  end as \"Dividendo\",\n  inv.name as Nome,\n  case\n    when inv.currency = \"USD\"\n      then CONCAT('R$ ', FORMAT(sum(dy.total - dy.fees) * $dolar, 2))\n    else CONCAT('R$ ', FORMAT(sum(dy.total - dy.fees), 2))\n  end  as \"Valor\",\n  DATE_FORMAT(dy.dueDate, '%d-%b') as 'Dt Pag'\nFROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere dy.status = \"PROVISIONED\" and inv.balance > 0 and cat.name in($category)\ngroup by inv.id, dy.dueDate\nORDER BY dy.updatedAt"
    }
   ]
  },
  {
   "title": "Dividendo Pago",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dy.updatedAt AS \"time\",\n  sum(case\n    when inv.currency = \"USD\"\n      then (dy.total - dy.fees) * $dolar\n    else (dy.total - dy.fees)\n  end) as \"Dividendo\",\n  cat.name as Nome,\n  case\n    when inv.currency = \"USD\"\n      then CONCAT('R$ ', FORMAT(sum(dy.total - dy.fees) * $dolar, 2)) \n    else CONCAT('R$ ', FORMAT(sum(dy.total - dy.fees), 2))\n  end as \"Valor\"\nFROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere dy.status = \"PAID\"\ngroup by inv.categoryId\nORDER BY dy.updatedAt"
    }
   ]
  },
  {
   "title": "(Dividendos)  Mês Atual x Mês Anterior",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(case\n    when inv.currency = \"USD\"\n      then (dy.total - dy.fees) * $dolar\n    else dy.total - dy.fees\n  end) as \"Mês Atual\"\nFROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere inv.balance > 0 and dy.dueDate > last_day(now() - INTERVAL 1 MONTH) and dy.dueDate <= last_day(now()) and cat.name in($category)"
    },
    {
     "rawSql": "SELECT \n  sum(case\n    when inv.currency = \"USD\"\n      then (dy.total - dy.fees) * $dolar\n    else dy.total - dy.fees\n  end) as \"Mês Anterior\"\nFROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere dy.status = \"PAID\" and dy.dueDate > last_day(now() - INTERVAL 2 MONTH) and dy.dueDate <= last_day(now() - INTERVAL 1 MONTH) and cat.name in($category)"
    }
   ]
  },
  {
   "title": "Renda Média Estimada (1M)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  sum(case\n    when inv.currency = \"USD\"\n      then (inv.qnt * dy.price) * $dolar\n    else inv.qnt * dy.price\n  end) from finance.dividends dy\ninner join finance.view_investment inv on inv.id = dy.investmentId\nwhere dy.id in (select max(tmp.id) from finance.dividends tmp where tmp.dueDate < last_day(now() - INTERVAL 1 MONTH) group by tmp.investmentId) and \ninv.category ->> \"$.name\" in($category);"
    }
   ]
  },
  {
   "title": "Eventos Coorporativos",
   "type": "marcusolsson-calendar-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_ADD(even.dateReference, INTERVAL 1 DAY) AS \"time\",\n  even.description AS metric,\n  even.link,\n  inv.name\nFROM finance.events even\ninner join finance.investment inv on inv.id = even.investmentId\nORDER BY even.dateReference"
    }
   ]
  },
  {
   "title": "Renda Média Estimada",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \ninv.name as \"Nome\",\nreplace(inv.category -> \"$.name\", '\"', '') as \"Categoria\",\ndy.price as \"Ùltimo dividendo\", \n((dy.price / inv.priceAverage) * 100) as \"Rendimento (%PM)\", \n((dy.price / inv.priceAverage) * 100) * 12 as \"Rendimento (%PM) 12M\"\nfrom finance.dividends dy\ninner join finance.view_investment inv on inv.id = dy.investmentId\nwhere dy.id in (select max(tmp.id) from finance.dividends tmp group by tmp.investmentId) and inv.balance > 0 and category ->>\"$.name\" in($category)\ngroup by dy.investmentId;"
    }
   ]
  },
  {
   "title": "Patrimônio por ativo",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  inv.updatedAt AS \"time\",\n  case\n    when inv.currency = \"USD\"\n      then inv.balance * $dolar\n    else inv.balance\n  end as \"Balanço\",\n  inv.name as Nome,\n  case\n    when inv.currency = \"USD\"\n      then CONCAT('R$ ', FORMAT(inv.balance * $dolar, 2)) \n    else CONCAT('R$ ', FORMAT(inv.balance, 2))\n  end as \"Valor\"\nFROM finance.investment inv\ninner join finance.category cat on cat.id = inv.categoryId\nwhere cat.name in($category) and inv.balance > 0\nORDER BY inv.updatedAt"
    }
   ]
  },
  {
   "title": "Patrimônio por categoria",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  inv.updatedAt as time_sec,\n  case\n    when inv.currency = \"USD\"\n      then sum(inv.balance) * $dolar\n    else sum(inv.balance)\n  end as \"Balanço\",\n  inv.sector as Nome\nFROM finance.investment inv\ninner join finance.category cat on cat.id = inv.categoryId\nwhere cat.name in($category) and inv.balance > 0\ngroup by inv.sector\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total de Dividendos pagos por ATIVO (FIIS)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(dy.total - dy.fees) AS \"Dividendo\",\n  (((select d.price from finance.dividends d where d.investmentId = dy.investmentId order by d.dueDate desc limit 1) / inv.priceAverage) * 100) as \"Rendimento (%PM)\", \n  (((select d.price from finance.dividends d where d.investmentId = dy.investmentId order by d.dueDate desc limit 1)/ inv.priceAverage) * 100) * 12 as \"Rendimento (%PM) 12M\",\n  inv.name as \"Nome\"\nFROM finance.dividends dy\ninner join finance.view_investment inv on inv.id = dy.investmentId\nwhere dy.status = \"PAID\" AND dy.total > 0 AND inv.category -> \"$.id\" = 1\ngroup by inv.id\nORDER BY sum(dy.total - dy.fees) asc"
    }
   ]
  },
  {
   "title": "Total de Dividendos pagos por ATIVO (AÇÃO)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(dy.total - dy.fees) AS \"Dividendo\",\n  (((select d.price from finance.dividends d where d.investmentId = dy.investmentId order by d.dueDate desc limit 1) / inv.priceAverage) * 100) as \"Rendimento (%PM)\", \n  (((select d.price from finance.dividends d where d.investmentId = dy.investmentId order by d.dueDate desc limit 1)/ inv.priceAverage) * 100) * 12 as \"Rendimento (%PM) 12M\",\n  inv.name as \"Nome\"\nFROM finance.dividends dy\ninner join finance.view_investment inv on inv.id = dy.investmentId\nwhere dy.status = \"PAID\" AND dy.total > 0 AND inv.category -> \"$.id\" = 2\ngroup by inv.id\nORDER BY sum(dy.total - dy.fees) asc"
    }
   ]
  },
  {
   "title": "Total de Dividendos pagos por ATIVO (ETF EX)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(case\n    when inv.currency = \"USD\"\n      then (dy.total - dy.fees) * $dolar\n    else dy.total - dy.fees \n  end) AS \"Dividendo\",\n  (((select d.price from finance.dividends d where d.investmentId = dy.investmentId order by d.dueDate desc limit 1) / inv.priceAverage) * 100) as \"Rendimento (%PM)\", \n  (((select d.price from finance.dividends d where d.investmentId = dy.investmentId order by d.dueDate desc limit 1)/ inv.priceAverage) * 100) * 12 as \"Rendimento (%PM) 12M\",\n  inv.name as \"Nome\"\nFROM finance.dividends dy\ninner join finance.view_investment inv on inv.id = dy.investmentId\nwhere dy.status = \"PAID\" AND dy.total > 0 AND inv.category -> \"$.id\" = 6\ngroup by inv.id\nORDER BY sum(dy.total - dy.fees) asc"
    }
   ]
  },
  {
   "title": "Total de Dividendos pagos por ATIVO (EQUITY)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(case\n    when inv.currency = \"USD\"\n      then (dy.total - dy.fees) * $dolar\n    else dy.total - dy.fees\n  end) AS \"Dividendo\",\n  (((select d.price from finance.dividends d where d.investmentId = dy.investmentId order by d.dueDate desc limit 1) / inv.priceAverage) * 100) as \"Rendimento (%PM)\", \n  (((select d.price from finance.dividends d where d.investmentId = dy.investmentId order by d.dueDate desc limit 1) / inv.priceAverage) * 100) * 12 as \"Rendimento (%PM) 12M\",\n  inv.name as \"Nome\"\nFROM finance.dividends dy\ninner join finance.view_investment inv on inv.id = dy.investmentId\nwhere dy.status = \"PAID\" AND dy.total > 0 AND inv.category -> \"$.id\" = 5\ngroup by inv.id\nORDER BY sum(dy.total - dy.fees) asc"
    }
   ]
  },
  {
   "title": "Total de Dividendos pagos por MÊS",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(\n     case \n      when inv.currency = \"USD\"\n        then (dy.total - dy.fees) * $dolar\n      else dy.total - dy.fees\n     end\n ) AS \"Dividendo\",\n DATE_FORMAT(dy.dueDate, \"%m/%y\") as \"Date\"\nFROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere dy.status = \"PAID\" AND dy.dueDate >= last_day(now() - INTERVAL 1 YEAR) and cat.name in($category)\nGROUP BY DATE_FORMAT(dy.dueDate, \"%m/%y\")\norder by dy.dueDate asc"
    }
   ]
  },
  {
   "title": "Total de Dividendos pagos",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(\n    case\n      when inv.currency = \"USD\"\n        then (dy.total - dy.fees) * $dolar\n      else dy.total - dy.fees\n    end\n  ) AS \"Dividendo\",\n  \"Total de dividendos recebidos\"\nFROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere dy.status = \"PAID\" and cat.name in($category)\nORDER BY dy.createdAt"
    }
   ]
  },
  {
   "title": "Patrimônio (Evolução)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_FORMAT(t.negotiationDate, \"%m/%y\") as \"Date\",\n  (\n    select \n      sum(case\n        when inv.currency = \"USD\"\n          then t2.total * $dolar\n        else t2.total\n      end)\n    from finance.transaction t2 \n    inner join finance.investment inv on inv.id = t2.investmentId\n    inner join finance.category cat on cat.id = inv.categoryId\n    where t2.negotiationDate <= LAST_DAY(t.negotiationDate) and cat.name in($category)\n  ) as \"Total Compra\"\nfrom finance.transaction t\ninner join finance.investment inv on inv.id = t.investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere t.negotiationDate >= last_day(now() - INTERVAL 1 YEAR) and cat.name in($category)\ngroup by DATE_FORMAT(negotiationDate, \"%m/%y\")\norder by t.negotiationDate asc;"
    }
   ]
  },
  {
   "title": "Movimentações",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n   DATE_FORMAT(negotiationDate, \"%m/%y\") as \"Date\",\n   sum(case\n    when inv.currency = \"USD\"\n      then total * $dolar\n    else total\n   end) AS \"Total Compra\"\nFROM finance.transaction\ninner join finance.investment inv on inv.id = investmentId  \ninner join finance.category cat on cat.id = inv.categoryId\nwhere `type` = \"BUY\" AND negotiationDate >= last_day(now() - INTERVAL 1 YEAR) and cat.name in($category)\nGROUP BY  DATE_FORMAT(negotiationDate, \"%m/%y\")\norder by negotiationDate asc"
    },
    {
     "rawSql": "SELECT\n  DATE_FORMAT(negotiationDate, \"%m/%y\") as \"Date\",\n  sum(case\n    when inv.currency = \"USD\"\n      then ABS(qnt) * price * $dolar\n    else ABS(qnt) * price\n  end) AS \"Total Venda\"\nFROM finance.transaction\ninner join finance.investment inv on inv.id = investmentId\ninner join finance.category cat on cat.id = inv.categoryId\nwhere `type` = \"SELL\" AND negotiationDate >= last_day(now() - INTERVAL 1 YEAR) and cat.name in($category)\nGROUP BY DATE_FORMAT(negotiationDate, \"%m/%y\")\norder by negotiationDate asc"
    }
   ]
  },
  {
   "title": "Dólar Americano (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.USDBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/USD-BRL"
    }
   ]
  },
  {
   "title": "Euro (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.EURBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/EUR-BRL"
    }
   ]
  },
  {
   "title": "Franco Suíço (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.CHFBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/CHF-BRL"
    }
   ]
  },
  {
   "title": "Dólar Canadense (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.CADBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/CAD-BRL"
    }
   ]
  },
  {
   "title": "Litecoin (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.LTCBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/LTC-BRL"
    }
   ]
  },
  {
   "title": "Dogecoin (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.DOGEBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/DOGE-BRL"
    }
   ]
  },
  {
   "title": "Bitcoin (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.BTCBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/BTC-BRL"
    }
   ]
  },
  {
   "title": "Ethereum (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.ETHBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/ETH-BRL"
    }
   ]
  }
 ]
}