{
 "title": "Finance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Patrimônio",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(balance) as \"Total\"\nFROM finance.investment"
    }
   ]
  },
  {
   "title": "Valor Atual da carteira (R$)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(variationTotal) as \"Total\"\nFROM finance.investment\nwhere priceDay is not null"
    }
   ]
  },
  {
   "title": "Cotação + Dividendos + Lucros/Prejuizo",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\n(select sum(total) from finance.dividends where status = \"PAID\") + \nsum(variationTotal) + \n(select sum(profit) from finance.transaction)\n) AS \"Total\"\nFROM finance.investment\nwhere priceDay is not null"
    }
   ]
  },
  {
   "title": "Lucros/Prejuizo Do Dia",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(variationDayTotal) AS \"Total\"\nFROM finance.view_investment"
    }
   ]
  },
  {
   "title": "Valor Atual da carteira (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n(SUM(variationTotal) / SUM(balance)) * 100 as \"Percentual\"\nFROM finance.investment\nwhere priceDay is not null"
    }
   ]
  },
  {
   "title": "Cotação do dia",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  updatedAt AS \"time\",\n  priceDay AS \"Preço\",\n  name\nFROM finance.investment\nwhere balance > 0\nORDER BY updatedAt "
    }
   ]
  },
  {
   "title": "Variação do dia",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  updatedAt AS \"time\",\n  variationDay AS \"Preço\",\n  name\nFROM finance.investment\nwhere balance > 0\nORDER BY updatedAt"
    }
   ]
  },
  {
   "title": "Carteira",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select\ninv.name as \"Código\",\ninv.qnt as \"Total de Cotas\",\ninv.balance as \"Total de Aportes\",\ninv.priceAverage as \"Preço Médio\",\n-- sum(dy.total / 100) as \"Dividendos Recebidos\",\ninv.priceDay as \"Cotação Hoje\",\nsum(inv.balance + inv.variationTotal) as \"Saldo Atual\",\ninv.variationTotal as \"Lucro/Prejuízo\",\ninv.changePercentTotal as \"Saldo (%)\",\ninv.percent as \"(%) Da Carteira\",\nreplace(inv.category -> \"$.name\", '\"', '') as \"Categoria\",\ninv.sector as \"Seguemento\"\nfrom finance.view_investment inv\n-- left join finance.dividends dy on dy.investmentId = inv.id\nwhere balance > 0\ngroup by inv.id\norder by inv.balance desc"
    }
   ]
  },
  {
   "title": "Últimas compras (1M)",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\ninv.name as \"Código\",\ntran.price as \"Preço\",\nDATE_FORMAT(tran.negotiationDate, \"%d/%m/%y\") as \"Data\"\nFROM finance.transaction tran\ninner join finance.investment inv on inv.id = tran.investmentId\nwhere tran.id in (SELECT max(id) from finance.transaction group by investmentId) and \nnegotiationDate > last_day(now() - INTERVAL 1 MONTH)\ngroup by inv.id\n"
    }
   ]
  },
  {
   "title": "Dividendo provisionado",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dy.updatedAt AS \"time\",\n  sum(dy.total - dy.fees) as \"Dividendo\",\n  inv.name as Nome,\n  CONCAT('R$ ', FORMAT(sum(dy.total - dy.fees), 2)) as \"Valor\",\n  DATE_FORMAT(dy.dueDate, '%d-%b') as 'Dt Pag'\nFROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\nwhere dy.status = \"PROVISIONED\" and inv.balance > 0\ngroup by inv.id\nORDER BY dy.updatedAt"
    }
   ]
  },
  {
   "title": "Renda Média Estimada (1M)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nsum(tran.qnt * dy.price) as \"Dividendo\"\nFROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\ninner join finance.transaction tran on inv.id = tran.investmentId\nwhere dy.dueDate > last_day(now() - INTERVAL 2 MONTH) and dy.dueDate < last_day(now() - INTERVAL 1 MONTH) and dy.status = \"PAID\" and inv.balance > 0\n\n"
    }
   ]
  },
  {
   "title": "(Dividendos)  Mês Atual x Mês Anterior",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(dy.total - dy.fees) as \"Mês Atual\"\nFROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\nwhere inv.balance > 0 and dy.dueDate > last_day(now() - INTERVAL 1 MONTH)"
    },
    {
     "rawSql": "SELECT sum(dy.total - dy.fees) as \"Mês Anterior\"\nFROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\nwhere dy.status = \"PAID\" and dy.dueDate > last_day(now() - INTERVAL 2 MONTH) and dy.dueDate <= last_day(now() - INTERVAL 1 MONTH)"
    }
   ]
  },
  {
   "title": "Total de Dividendos pagos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(dy.total - dy.fees ) AS \"Dividendo\",\n  \"Total de dividendos recebidos\"\nFROM finance.dividends dy\nwhere dy.status = \"PAID\"\nORDER BY dy.createdAt"
    }
   ]
  },
  {
   "title": "Eventos Coorporativos",
   "type": "marcusolsson-calendar-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_ADD(even.dateReference, INTERVAL 1 DAY) AS \"time\",\n  even.description AS metric,\n  even.link,\n  inv.name\nFROM finance.events even\ninner join finance.investment inv on inv.id = even.investmentId\nORDER BY even.dateReference"
    }
   ]
  },
  {
   "title": "Patrimônio (Evolução)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n   DATE_FORMAT(t.negotiationDate, \"%m/%y\") as \"Date\",\n    (select sum(t2.total) from finance.transaction t2 where t2.negotiationDate <= LAST_DAY(t.negotiationDate)) as \"Total Compra\"\nfrom finance.transaction t\ngroup by DATE_FORMAT(negotiationDate, \"%m/%y\")\norder by t.negotiationDate asc\nLIMIT 12;"
    }
   ]
  },
  {
   "title": "Patrimônio por ativo",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  updatedAt AS \"time\",\n  balance as \"Balanço\",\n  name as Nome,\n  CONCAT('R$ ', FORMAT(balance, 2)) as \"Valor\"\nFROM finance.investment\nwhere balance > 0\nORDER BY updatedAt"
    }
   ]
  },
  {
   "title": "Patrimônio por categoria",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  updatedAt as time_sec,\n  sum(balance) as \"Balanço\",\n  sector as Nome\nFROM finance.investment\nwhere balance > 0\ngroup by sector\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total de Dividendos pagos por ATIVO",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(dy.total - dy.fees) AS \"Dividendo\",\n  inv.name\nFROM finance.dividends dy\ninner join finance.investment inv on inv.id = dy.investmentId\nwhere dy.status = \"PAID\" AND dy.total > 0\ngroup by inv.id\nORDER BY sum(dy.total - dy.fees) asc"
    }
   ]
  },
  {
   "title": "Total de Dividendos pagos por MÊS",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(total - fees) AS \"Dividendo\",\n  DATE_FORMAT(dueDate, \"%m/%y\") as \"Date\"\nFROM finance.dividends\nwhere status = \"PAID\"\nGROUP BY DATE_FORMAT(dueDate, \"%m/%y\")\norder by dueDate asc\nLIMIT 12"
    }
   ]
  },
  {
   "title": "Movimentações",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n   DATE_FORMAT(negotiationDate, \"%m/%y\") as \"Date\",\n  sum(total) AS \"Total Compra\"\nFROM finance.transaction\nwhere `type` = \"BUY\"\nGROUP BY  DATE_FORMAT(negotiationDate, \"%m/%y\")\norder by negotiationDate asc\nLIMIT 12"
    },
    {
     "rawSql": "SELECT\n  DATE_FORMAT(negotiationDate, \"%m/%y\") as \"Date\",\n  sum(ABS(qnt) * price) AS \"Total Venda\"\nFROM finance.transaction\nwhere `type` = \"SELL\"\nGROUP BY DATE_FORMAT(negotiationDate, \"%m/%y\")\norder by negotiationDate asc\nLIMIT 12"
    }
   ]
  },
  {
   "title": "Dólar Americano (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.USDBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/USD-BRL"
    }
   ]
  },
  {
   "title": "Euro (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.EURBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/EUR-BRL"
    }
   ]
  },
  {
   "title": "Franco Suíço (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.CHFBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/CHF-BRL"
    }
   ]
  },
  {
   "title": "Dólar Canadense (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.CADBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/CAD-BRL"
    }
   ]
  },
  {
   "title": "Litecoin (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.LTCBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/LTC-BRL"
    }
   ]
  },
  {
   "title": "Dogecoin (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.DOGEBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/DOGE-BRL"
    }
   ]
  },
  {
   "title": "Bitcoin (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.BTCBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/BTC-BRL"
    }
   ]
  },
  {
   "title": "Ethereum (compra)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.ETHBRL.bid", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/last/ETH-BRL"
    }
   ]
  }
 ]
}