export const tokens = { 
    Config: Symbol("Config"),
    Routes: Symbol("Routes"),
    RepositoryBase: Symbol("RepositoryBase"),
    RedisClient: Symbol("RedisClient"),
    ApmClient: Symbol("ApmClient"),
    EmailClient: Symbol("EmailClient"),
    SystemRouter: Symbol("SystemRouter"),
    HealthcheckController: Symbol("HealthcheckController"),
    SystemService: Symbol("SystemService"),
    SystemRepository: Symbol("SystemRepository"),
    CategoryRouter: Symbol("CategoryRouter"),
    FindByIdCategoryController: Symbol("FindByIdCategoryController"),
    FindAllCategoryController: Symbol("FindAllCategoryController"),
    CreateCategoryController: Symbol("CreateCategoryController"),
    DeleteCategoryController: Symbol("DeleteCategoryController"),
    UpdateCategoryController: Symbol("UpdateCategoryController"),
    CategoryRepository: Symbol("CategoryRepository"),
    CategoryService: Symbol("CategoryService"),
    ProductRouter: Symbol("ProductRouter"),
    FindByIdProductController: Symbol("FindByIdProductController"),
    FindAllProductController: Symbol("FindAllProductController"),
    CreateProductController: Symbol("CreateProductController"),
    DeleteProductController: Symbol("DeleteProductController"),
    UpdateProductController: Symbol("UpdateProductController"),
    ProductRepository: Symbol("ProductRepository"),
    ProductService: Symbol("ProductService"),
};